/**
 * @description       : 
 * @author            : Braulio Villares Torres
 * @group             : 
 * @last modified on  : 06-17-2022
 * @last modified by  : Braulio Villares Torres
**/
public without sharing class AccountTriggerHelper {
    
    public AccountTriggerHelper() {
        System.debug('Inside AccountTriggerHelper Constructor');
    }

    public void doTask1() {
        System.debug('Inside Task 1');
    }

    public void doTask2() {
        System.debug('Inside Task 2');
    }

    public void doTask3() {
        System.debug('Inside Task 3');
    }

    public void doTask4() {
        System.debug('Inside Task 4');
    }

    public void doTask5() {
        System.debug('Inside Task 5');
    }
    
}
